frontend/views/main.py
#!/usr/bin/python3
"""flask """

from flask import flash, Blueprint, render_template, request, redirect, url_for
from datetime import datetime


main_bp = Blueprint("main", __name__)

@main_bp.route('/')
def home():
    """logics for the home page"""
    
    
    return render_template(
        'main/home.html'
    )

@main_bp.route('/contact-us')
def contact_us():
    """logics for the contact us page"""
    
    return render_template(
        'main/contact_us.html'
    )

@main_bp.route('/about-us')
def about_us():
    """logics for the about us page"""
    
    return render_template(
        'main/about_us.html'
    )

@main_bp.route('/privacy-policy')
def privacy_policy():
    """logics for the about us page"""
    
    return render_template(
        'main/privacy_policy.html'
    )



@main_bp.route('/learn', defaults={'topic': None})
@main_bp.route('/learn/<string:topic>')
def learn(topic=None):
    """logics for the learning page"""

    if topic is None:
        return render_template(
            'main/learn.html'
        )
    else:
        temlate_path = f"learn/{topic}.html"
        try:
            return render_template(
                temlate_path
            )
        except:
            msg = "No such leaarning"
            return render_template(
                'main/learn.html',
                msg=msg
            )

frontend/templates/main/about_us.html
<h1>About Page</h1>

frontend/templates/main/contact_us.html
<h1>Contact us</h1>

frontend/templates/main/home.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main/home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block additinal_nav%}

{% endblock %}



{% block content %}
<main class="main">
  <section class="mini-video">
    <div class="container text-center hero-video">
      <video class="" width="200" height="200" autoplay loop muted>
        <source src="{{ url_for('static', filename='videos/adsvid.mp4') }}" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('auth.login')}}"><button class="btn btn-primary " type="submit">Signin</button></a>
      {% endif %}
    </div>
  </section>

  
  <section class="service">
    <h2 class="mb-2 text text-center">Featured services</h2>
    <p class="container">Do you need an experienced person to do your job? find the services and the artisans you need here</p>
    <div class="container row row-cols-1 row-cols-md-3 text-center service-container ">
      <div class="col mb-3">
        <div class="card h-100">
          <img src="{{ url_for('static', filename='images/tailor.jpeg') }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Plumbing</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
      <div class="col mb-3">
        <div class="card h-100">
          <img src="{{ url_for('static', filename='images/tailor.jpeg') }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Tailoring</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
      <div class="col mb-3">
        <div class="card h-100">
          <img src="{{ url_for('static', filename='images/tailor.jpeg') }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Welding</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
      <div class="col mb-3">
        <div class="card h-100">
          <img src="{{ url_for('static', filename='images/tailor.jpeg') }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Cleaning</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
    </div>
  </section>

  

  <section>
    <div class="text-center m">
      <div class="container">
        <form class="" role="search">
          <input class="form-control me-2 mb-3" type="search" placeholder="Search for a service" aria-label="Search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>
      </div>
    </div>
  </section>

  <section>
    <div class="container my-5">
      <h2 class="text-center mb-4">Frequently Asked Questions</h2>
      <div class="accordion" id="faqAccordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              How to book for a service?
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              Our mission is to provide high-quality products and excellent customer service to our valued customers.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              How can I place an order?
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              You can place an order through our website or by contacting our customer service representatives.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Do you offer any discounts or promotions?
            </button>
          </h2>
          <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              Yes, we frequently offer discounts and promotions. Please check our website or subscribe to our newsletter to stay updated.
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <section>
    <div class="container my-5">
      <h2 class="text-center mb-1">Testimonials and Reviews</h2>
      <p class="text-center mb-2">What people are saying about Craftdot</p>
      <div id="testimonialsCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="card">
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                  <div class="text-center mb-2 rating">&#9733;&#9733;&#9733;&#9733;&#9733;</div>
                  <p>"I've been using this product for years, and I'm incredibly satisfied with its performance and durability. Highly recommended!"</p>
                  <footer class="blockquote-footer">John Doe, <cite title="Source Title">Happy Customer</cite></footer>
                </blockquote>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="card">
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                  <div class="text-center mb-2 rating">&#9733;&#9733;&#9733;&#9733;&#9733;</div>
                  <p>"The customer service team is exceptional! They went above and beyond to ensure my issue was resolved quickly and efficiently."</p>
                  <footer class="blockquote-footer">Jane Smith, <cite title="Source Title">Satisfied Client</cite></footer>
                </blockquote>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="card">
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                  <div class="text-center mb-2 rating">&#9733;&#9733;&#9733;&#9733;&#9733;</div>
                  <p>"This product has exceeded my expectations in every way. It's user-friendly, efficient, and offers great value for money."</p>
                  <footer class="blockquote-footer">Michael Johnson, <cite title="Source Title">Loyal Customer</cite></footer>
                </blockquote>
              </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#testimonialsCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#testimonialsCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </section>

  {% if not current_user.is_authenticated %}
  <div class="text-center mb-2">
    <p>Signin to get access to many good services in your location</p>
    <a href="{{ url_for('auth.login')}}"><button class="btn btn-primary " type="submit">Signin</button></a>
  </div>
  {% endif %}
  




  
        

</main>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/main/home.js') }}"></script>
{% endblock %}

frontend/templates/main/learn.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main/learn.css') }}">
{% endblock %}

{% block title %}Learn Crypto{% endblock %}

{% block headers %} {% endblock %}

{% block content %}

<main>
  <section class="learn-container">
    <div class="container mb-4">
        <h4>Learning links for me</h4>
        <ul>
            <li><a href="{{ url_for('main.learn', topic='crypto') }}" target="_blank" rel="noopener noreferrer">
                learn crypto
              </a>
            </li>
            <li>
            <a href="{{ url_for('main.learn', topic='forex') }}" target="_blank" rel="noopener noreferrer">
                learn forex
            </a>
            </li>
        </ul>
    </div>
  </section>
</main>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/main/learn.js') }}"></script>
{% endblock %}

frontend/templates/main/privacy_policy.html
<h1>Privacy Policy</h1>