frontend/views/account.py
#!/usr/bin/python3
"""flask user account for craftdot"""



from flask import flash, Blueprint, render_template, request, redirect, url_for
from datetime import datetime
from flask_login import current_user, login_required
from frontend.loginmodel import User
import requests


account_bp = Blueprint("account", __name__, url_prefix='/account')


@account_bp.route('/profile')
@login_required
def profile():
    """user profiles algo"""

    # Get user id
    user_id = current_user.id
    api_url = f"http://127.0.0.1:8000/api/v1/users/{user_id}"
    response = requests.get(api_url)
    if response.status_code == 200:
        user_data = response.json()
    else:
        user_data = None 
    return render_template(
        'account/profile.html',
        user_data=user_data,
    )

@account_bp.route('/password')
@login_required
def change_password():
    """ Change user password"""
    return render_template(
        'account/change_password.html',
    )

@account_bp.route('/my-tasks')
@login_required
def my_tasks():
    """ Change user password"""
    return render_template(
        'account/my_tasks.html',
    )

@account_bp.route('/notification')
@login_required
def notification():
    """ Change user password"""
    return render_template(
        'account/notification.html',
    )

#sample test to create artisan
@account_bp.route('/create', methods=['GET', 'POST'])
def create_artisan():
    """logics for the home page"""
    if request.method == 'POST':

        # Create artisans from the form data

        form_data = request.form.to_dict()
        #name = form_data['name']
        #skill = form_data['skill']
        #availability = form_data['availability']
        url = 'http://127.0.0.1:8000/api/v1/artisans'
       
        headers = {
            'Content-Type': 'application/json',
        }

        r = requests.post(url, json=form_data, headers=headers)
        if r.status_code == 201:
            flash('Artisan created successfully', 'success')
        else:
            flash('Failed to create artisan', 'danger')
        return render_template(
        'account/create_artisan.html',
        )
    
    if request.method == 'GET':
        service_url = 'http://127.0.0.1:8000/api/v1/services'
        # return all services data
        r = requests.get(service_url)
        if r.status_code == 200:
            services = r.json()
            print(services)
        else:
            services = None

        return render_template(
        'account/create_artisan.html',
        services=services
        )

frontend/views/main.py
#!/usr/bin/python3
"""flask """

from flask import flash, Blueprint, render_template, request, redirect, url_for
from datetime import datetime


main_bp = Blueprint("main", __name__)

@main_bp.route('/')
def home():
    """logics for the home page"""
    
    
    return render_template(
        'main/home.html'
    )

@main_bp.route('/contact-us')
def contact_us():
    """logics for the contact us page"""
    
    return render_template(
        'main/contact_us.html'
    )

@main_bp.route('/about-us')
def about_us():
    """logics for the about us page"""
    
    return render_template(
        'main/about_us.html'
    )

@main_bp.route('/privacy-policy')
def privacy_policy():
    """logics for the about us page"""
    
    return render_template(
        'main/privacy_policy.html'
    )



@main_bp.route('/learn', defaults={'topic': None})
@main_bp.route('/learn/<string:topic>')
def learn(topic=None):
    """logics for the learning page"""

    if topic is None:
        return render_template(
            'main/learn.html'
        )
    else:
        temlate_path = f"learn/{topic}.html"
        try:
            return render_template(
                temlate_path
            )
        except:
            msg = "No such leaarning"
            return render_template(
                'main/learn.html',
                msg=msg
            )

frontend/views/service.py
#!/usr/bin/python3
"""flask homepage for birthday celebration app"""

from flask import flash, Blueprint, render_template, request, redirect, jsonify, url_for, abort
from datetime import datetime
import requests
from frontend.app import cache
from flask import current_app as app
from flask_login import current_user, login_required
import json


service_bp = Blueprint("service", __name__, url_prefix="/services")

@service_bp.route('/')
@cache.cached(timeout=30)
def service():
    """logics for the home page"""

    service_url = f'http://127.0.0.1:8000/api/v1/services'
    r = requests.get(service_url)
    if r.status_code == 200:
        service = r.json()
        services = service

    else:
        services = None
    
    return render_template(
        'services/services.html',
        services=services,
    )
    

@service_bp.route('/booking')
@cache.cached(timeout=30)
def booking():
    """logics for booking details"""

    service_url = f'http://127.0.0.1:8000/api/v1/services'
    r = requests.get(service_url)
    if r.status_code == 200:
        service = r.json()
        services = service

    else:
        services = None
 
    return render_template(
        'services/booking.html',
        services=services,
    )


@service_bp.route('/booking/<string:service_id>')
@login_required
@cache.cached(timeout=30)
def booking_detail(service_id):
    """logics for booking details"""
    # Get the name of the service
    r = requests.get(f'http://127.0.0.1:8000/api/v1/services/{service_id}')
    if r.status_code == 200:
        service = r.json()
        service_name = service['name']

    else:
        if r.status_code == 404:
            return abort(404)
        
    # Get all the states and LGAS
    with open('country_data/state.json', 'r') as f:
        all_state = json.load(f)
        states = []
        for state in all_state['geonames']:
            state_name = state['name'].split(" ")[0] # split and pick only state name
            # Append each state to alist
            states.append(state_name)
            # Arrange the states alphabetically
            states.sort()
    # Get all the LGAs
    with open('country_data/LGA.json', 'r') as f:
        all_LGA = json.load(f)
        LGAs = []
        for lga in all_LGA['geonames']:
            lga_name = lga['name']
            lga_state = lga['adminName1'].split(" ")[0]
            data = {
                'LGA': lga_name,
                'state': lga_state
            }
            LGAs.append(data)

        lga_data = {state: [] for state in states}

        for lga in LGAs:
            state = lga['state']
            lga_name = lga['LGA']
            if state in lga_data:
                lga_data[state].append(lga_name)
        lga_data=lga_data
            

    return render_template(
        'services/booking_details.html',
        service_name=service_name,
        service_id=service_id,
        states=states,
        lga_data=lga_data
    )


@service_bp.route('/booking/recommendation/<service_id>', methods=['GET', 'POST'], endpoint='booking_recommendation')
@login_required
#@cache.cached(timeout=30)
def booking_recommendation(service_id):
    """logics for booking recommendation"""
    if request.method == 'POST':
        # Get form data
        user_task_details = request.form.to_dict()
        #Get service name
        r = requests.get(f'http://127.0.0.1:8000/api/v1/services/{service_id}')
        if r.status_code == 200:
            service = r.json()
            service_name = service['name']

        else:
            if r.status_code == 404:
                return abort(404)

        # Get all artisans before recommendation
        r = requests.get('http://127.0.0.1:8000/api/v1/artisans')
        if r.status_code == 200:
            all_artisans = r.json()

            # This is where the app algorithim lies, connect users to artisans based on location, ...
            # Merging artisans and users
            # List all artisans with the same service the user want
            artisans_with_similar_service = []
            artisans_user_data = []
            for artisan in all_artisans:
                if artisan['service_id'] == service_id:
                    artisans_with_similar_service.append(artisan)
                    # Get the artisan user datas using artisan user_id
                    artisan_user_id = artisan['user_id']
                    r = requests.get(f'http://127.0.0.1:8000/api/v1/users/{artisan_user_id}')
                    if r.status_code == 200:
                        artisan_user = r.json()
                        artisans_user_data.append(artisan_user)
                    else:
                        artisan_user = None

            artisans = artisans_with_similar_service
            artisans_user_data = artisans_user_data

            
        else:
            artisans = None
        artisans = artisans

        return render_template(
        'services/booking_recommendation.html',
        service_name=service_name,
        artisans=artisans,
        artisans_user_data = artisans_user_data,
        service_id=service_id,
        user_task_details=user_task_details
        )
    else:
        return redirect(url_for('service.booking'))


@service_bp.route('/booking/confirm/<service_id>',  methods=['GET', 'POST'])
@login_required
@cache.cached(timeout=30)
def booking_confirm(service_id):
    """logics for booking details"""

    # Get recaptcha site key
    recaptcha_site_key = app.config['RECAPTCHA_SITE_KEY']
    


    if request.method == 'POST':
        user_request = request.form.to_dict()
        booking = user_request

        return render_template(
            'services/booking_confirm.html',
            booking=booking,
            service_id=service_id,
            recaptcha_site_key=recaptcha_site_key,
        )
    
    else:
        return redirect(url_for('service.booking'))
    


@service_bp.route('/book/task',  methods=['GET', 'POST'])
@login_required
@cache.cached(timeout=30)
def book_task():
    """logics for booking details"""

    # Get recaptcha secret keys
    recaptcha_secret_key = app.config['RECAPTCHA_SECRET_KEY']
    # Get current user
    user_id=current_user.id

    if request.method == 'POST':
        recaptcha_response = request.form['g-recaptcha-response']
        data = {
            'secret': recaptcha_secret_key,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()
        if not result['success']:
            flash('Invalid recaptcha. Please try again', 'danger')
            #return redirect(url_for('service.booking'))
            return jsonify({'message': 'reCAPTCHA verification failed'}), 400
        
        # Get form data
        form_data = request.form.to_dict()
        # del recapcha key-value from the form data
        form_data.pop('g-recaptcha-response')
        # Add user_id to the form
        user_id = {'user_id': user_id}
        form_data.update(user_id)

        # Create Booking
        booking_url = 'http://127.0.0.1:8000/api/v1/bookings'
       
        headers = {
            'Content-Type': 'application/json',
        }

        r = requests.post(booking_url, json=form_data, headers=headers)
        if r.status_code == 201:
            response = r.json()
            
        else:
            response = {
                'code': r.status_code,
                'message': r.content
            }

        
        return render_template(
            'services/booking_success.html',
            result=result,
            response=response,
            d=form_data
        ) 
    else:
        return redirect(url_for('service.booking'))

frontend/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Craftdot - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous">
     <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <script
    src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
    crossorigin="anonymous"></script>
    {% endblock %}
  </head>

  {% block header %}
    <nav class="navbar navbar-expand-lg fixed-top bg-body-tertiary ">
      <div class="container-fluid">
          <h1><a href="{{ url_for('main.home')}}">Craftdot</a></h1>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('service.service')}}">Find services</a>
              </li>
              
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('service.booking')}}">Book a service</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('service.booking')}}">My Tasks</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('account.profile')}}">Account</a>
              </li>
              {% else %}
              <a class="nav-link" href="{{ url_for('auth.login')}}">Login/Signup</a>
              <li class="nav-item">
                <a class="nav-link" href="#">Become a crafter</a>
              </li>

              {% endif %}

              
              {% block additional_nav %} {% endblock %}
          </ul>
          </div>
      </div>
    </nav>
    {% endblock header %}

  <body>
    

    <div class="container">
      {% block flashmessage %}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          <div class=flash id="flashMessage">
          {% for category, message in messages %}
            <li class="{{ category }}-msg">{{ message }}</li>
          {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
      {% endblock flashmessage %} 

      {% block content %} {% endblock content %}
    </div>
    
  
    {% block footer %}
    <footer>
      <div class="footer-links">
        <a href="#">About us</a>
        <a href="{{ url_for('service.booking')}}">Book a service</a>
        <a href="#">Become a craftsdotter</a>
        <a href="#">Signup</a>
      </div>
      <div class="footer-links">
        <a href="#">Contact us</a>
        <a href="#">Terms of service</a>
        <a href="#">Privacy policy</a>
        <a href="#">All services</a>
      </div>

      <div class="app-links">
        <a href="#">
            <img src="{{ url_for('static', filename='images/appstore_badge.png')}}" alt="Download on the App Store">
        </a>
        <a href="#">
            <img src="{{ url_for('static', filename='images/googleplay_badge.pn')}}" alt="Get it on Google Play">
        </a>
      </div>
        <p>&copy; Craftdot 2024. All rights reserved.</p>
    </footer>
    {% endblock %}

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>