frontend/views/service.py
#!/usr/bin/python3
"""flask homepage for birthday celebration app"""

from flask import flash, Blueprint, render_template, request, redirect, jsonify, url_for, abort
from datetime import datetime
import requests
from frontend.app import cache
from flask import current_app as app
from flask_login import current_user, login_required
import json


service_bp = Blueprint("service", __name__, url_prefix="/services")

@service_bp.route('/')
@cache.cached(timeout=30)
def service():
    """logics for the home page"""

    service_url = f'http://127.0.0.1:8000/api/v1/services'
    r = requests.get(service_url)
    if r.status_code == 200:
        service = r.json()
        services = service

    else:
        services = None
    
    return render_template(
        'services/services.html',
        services=services,
    )
    

@service_bp.route('/booking')
@cache.cached(timeout=30)
def booking():
    """logics for booking details"""

    service_url = f'http://127.0.0.1:8000/api/v1/services'
    r = requests.get(service_url)
    if r.status_code == 200:
        service = r.json()
        services = service

    else:
        services = None
 
    return render_template(
        'services/booking.html',
        services=services,
    )


@service_bp.route('/booking/<string:service_id>')
@login_required
@cache.cached(timeout=30)
def booking_detail(service_id):
    """logics for booking details"""
    # Get the name of the service
    r = requests.get(f'http://127.0.0.1:8000/api/v1/services/{service_id}')
    if r.status_code == 200:
        service = r.json()
        service_name = service['name']

    else:
        if r.status_code == 404:
            return abort(404)
        
    # Get all the states and LGAS
    with open('country_data/state.json', 'r') as f:
        all_state = json.load(f)
        states = []
        for state in all_state['geonames']:
            state_name = state['name'].split(" ")[0] # split and pick only state name
            # Append each state to alist
            states.append(state_name)
            # Arrange the states alphabetically
            states.sort()
    # Get all the LGAs
    with open('country_data/LGA.json', 'r') as f:
        all_LGA = json.load(f)
        LGAs = []
        for lga in all_LGA['geonames']:
            lga_name = lga['name']
            lga_state = lga['adminName1'].split(" ")[0]
            data = {
                'LGA': lga_name,
                'state': lga_state
            }
            LGAs.append(data)

        lga_data = {state: [] for state in states}

        for lga in LGAs:
            state = lga['state']
            lga_name = lga['LGA']
            if state in lga_data:
                lga_data[state].append(lga_name)
        lga_data=lga_data
            

    return render_template(
        'services/booking_details.html',
        service_name=service_name,
        service_id=service_id,
        states=states,
        lga_data=lga_data
    )


@service_bp.route('/booking/recommendation/<service_id>', methods=['GET', 'POST'], endpoint='booking_recommendation')
@login_required
#@cache.cached(timeout=30)
def booking_recommendation(service_id):
    """logics for booking recommendation"""
    if request.method == 'POST':
        # Get form data
        user_task_details = request.form.to_dict()
        #Get service name
        r = requests.get(f'http://127.0.0.1:8000/api/v1/services/{service_id}')
        if r.status_code == 200:
            service = r.json()
            service_name = service['name']

        else:
            if r.status_code == 404:
                return abort(404)

        # Get all artisans before recommendation
        r = requests.get('http://127.0.0.1:8000/api/v1/artisans')
        if r.status_code == 200:
            all_artisans = r.json()

            # This is where the app algorithim lies, connect users to artisans based on location, ...
            # Merging artisans and users
            # List all artisans with the same service the user want
            artisans_with_similar_service = []
            artisans_user_data = []
            for artisan in all_artisans:
                if artisan['service_id'] == service_id:
                    artisans_with_similar_service.append(artisan)
                    # Get the artisan user datas using artisan user_id
                    artisan_user_id = artisan['user_id']
                    r = requests.get(f'http://127.0.0.1:8000/api/v1/users/{artisan_user_id}')
                    if r.status_code == 200:
                        artisan_user = r.json()
                        artisans_user_data.append(artisan_user)
                    else:
                        artisan_user = None

            artisans = artisans_with_similar_service
            artisans_user_data = artisans_user_data

            
        else:
            artisans = None
        artisans = artisans

        return render_template(
        'services/booking_recommendation.html',
        service_name=service_name,
        artisans=artisans,
        artisans_user_data = artisans_user_data,
        service_id=service_id,
        user_task_details=user_task_details
        )
    else:
        return redirect(url_for('service.booking'))


@service_bp.route('/booking/confirm/<service_id>',  methods=['GET', 'POST'])
@login_required
@cache.cached(timeout=30)
def booking_confirm(service_id):
    """logics for booking details"""

    # Get recaptcha site key
    recaptcha_site_key = app.config['RECAPTCHA_SITE_KEY']
    


    if request.method == 'POST':
        user_request = request.form.to_dict()
        booking = user_request

        return render_template(
            'services/booking_confirm.html',
            booking=booking,
            service_id=service_id,
            recaptcha_site_key=recaptcha_site_key,
        )
    
    else:
        return redirect(url_for('service.booking'))
    


@service_bp.route('/book/task',  methods=['GET', 'POST'])
@login_required
@cache.cached(timeout=30)
def book_task():
    """logics for booking details"""

    # Get recaptcha secret keys
    recaptcha_secret_key = app.config['RECAPTCHA_SECRET_KEY']
    # Get current user
    user_id=current_user.id

    if request.method == 'POST':
        recaptcha_response = request.form['g-recaptcha-response']
        data = {
            'secret': recaptcha_secret_key,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()
        if not result['success']:
            flash('Invalid recaptcha. Please try again', 'danger')
            #return redirect(url_for('service.booking'))
            return jsonify({'message': 'reCAPTCHA verification failed'}), 400
        
        # Get form data
        form_data = request.form.to_dict()
        # del recapcha key-value from the form data
        form_data.pop('g-recaptcha-response')
        # Add user_id to the form
        user_id = {'user_id': user_id}
        form_data.update(user_id)

        # Create Booking
        booking_url = 'http://127.0.0.1:8000/api/v1/bookings'
       
        headers = {
            'Content-Type': 'application/json',
        }

        r = requests.post(booking_url, json=form_data, headers=headers)
        if r.status_code == 201:
            response = r.json()
            
        else:
            response = {
                'code': r.status_code,
                'message': r.content
            }

        
        return render_template(
            'services/booking_success.html',
            result=result,
            response=response,
            d=form_data
        ) 
    else:
        return redirect(url_for('service.booking'))

frontend/templates/services/booking.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/booking.css') }}">
{% endblock %}


{% block title %}Booking{% endblock %}

{% block additional_nav%} {% endblock %}



{% block content %}
<main class="main">

  <section>
    <div class="text-center m">
      <div class="container">
        <form class="" role="search">
          <input class="form-control me-2 mb-3" type="search" placeholder="Search for a service" aria-label="Search">
          <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
      </div>
    </div>
  </section>
  
  <section>
    <div class="services">
      {% if services %}
      <p class="text-center">Pick your service from the list</p>
      <div class="services-list">
        {% for service in services %}
        <a href="{{ url_for('service.booking_detail', service_id=service.id) }}" class="service-link"><button type="submit" class="btn btn-outline-info service">{{ service.name }}</button></a>
        {% endfor %}
      </div>
      {% else %}
      <p class="text-center">No Service yet</p>
      {% endif %}
    </div>
  </section>

</main>

{% endblock %}

{% block footer %} {% endblock footer%}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/services/booking.js') }}"></script>
{% endblock %}

frontend/templates/services/booking_confirm.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/booking_confirm.css') }}">
{% endblock %}

{% block title %}Booking Confirm{% endblock %}
{% block header %}{% endblock %}

{% block flashmessage %}
{{ super() }}
{% endblock %}



{% block content %}
<main class="main">
  <section>
    <form id="bookingForm" method="post" action="#">
      <div class="card-header">
        <h4 class="text-center">{{ booking.service_name}} </h4>
        <img src="{{ booking.artisan_profile_picture}}" alt="{{ booking.artisan_name }}">
        <p>{{ booking.artisan_name }}</p>
        <p></p>
      </div>
      <div class="mt-2">
        <p>{{ booking.date}} at {{ booking.time}}</p>
        <p>2 HOUR MINIMUM</p>
        <p>{{ booking.address}}, {{booking.LGA}}, {{ booking.state }}</p>
        <p>{{ booking.size }}</p>
      </div>
      <div class="col-12">
        <p>Your task details</p>
        <textarea class="form-control" name="description" id="taskDescription" rows="5" maxlength="100" aria-valuenow="hhhhh" spellcheck="true" ></textarea>
      </div>
      <div>
        <h5>Price Details</h5>
        <p>Hourly Rate #{{ booking.artisan_price}}/hr </p>
        <p>You may see a temporary hold on your payment method in the amount of your Tasker's hourly rate of #{{ booking.artisan_price}}. You can cancel at any time. Tasks cancelled less than 24 hours before the start time may be billed a cancellation fee of one hour. Tasks have a one-hour minimum.</p>
        <p>Please follow all public health regulations in your area. Learn more.</p>
      </div>
      <div>
        <h5>Payment Method</h5>
        <div class="task-option col-12">
          <div class="form-check">
            <input class="form-check-input" type="radio" value="Online payment at job completion" name="payment_type" id="paymentType" checked>
            <label class="form-check-label" for="payment_type">
              Online payment
            </label>
            <p><small>Pay at job completion</small></p>
            <p><small>Get 10% of your total payment when you pay online</small></p>
            <p><small>Pay #3000 instead of  <strike class="text-bold text-danger">#{{ booking.artisan_price }}</strike> when you pay online</small></p>
          </div>
          <div class="form-check">
            <input class="form-check-input" value="Cash payment at job completion" type="radio" name="payment_type" id="paymentType">
            <label class="form-check-label" for="payment_type">
              Cash payment at job completion
            </label>
            <p><small>Pay at job completion</small></p>
          </div>
        </div>
      </div>
      <button type="button" class="btn btn-primary " data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Confirm and Chat
      </button>
      <p>Don’t worry, you won’t be billed until your task is complete. Once confirmed, you can chat with your Tasker to update the details.</p>
    </form>
  </section>

  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog .modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <img src="" alt="" id="arisanImage" class="artisan-image">
          <h1 class="modal-title fs-5 headerTexts" id="staticBackdropLabel headerText">
          </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form id="recaptcha" method="post" action="/services/book/task">
          <div class="modal-body" id="modalBodyContent"><br/>
            <div class="g-recaptcha" data-sitekey="{{ recaptcha_site_key}}"></div>
            <br/>
            <!-- Send the datas to the backend for booking processing-->
            <input type="text" name="service_id" value="{{ service_id}}" hidden>
            <input type="text" name="artisan_id" value="{{ booking.artisan_id}}" hidden>
            <input type="text" name="job_date" value="{{ booking.date}}" hidden>
            <input type="text" name="job_time" value="{{ booking.time}}" hidden>
            <input type="text" name="job_price" value="{{ booking.artisan_price }}" hidden>
            <input type="text" name="job_address" value="{{ booking.address}}" hidden>
            <input type="text" name="job_state" value="{{ booking.state}}" hidden>
            <input type="text" name="job_LGA" value="{{ booking.LGA}}" hidden>
            <input type="text" name="job_size" value="{{ booking.size}}" hidden>
            <input type="text" name="job_description" value="{{ booking.description}}" hidden>
            <!-- This psyment type is dynamically updated from jquery-->
            <input id="thePaymentType" type="text" name="payment_type" hidden>
            <input type="submit" value="Submit" class="btn btn-primary text-center">
          </div>
        </form>
      </div>
    </div>
  </div>
  



</main>

{% endblock %}

{% block footer %}{% endblock %}

{% block scripts %}
{{ super() }}
<!-- Embedding data in a script tag as JSON -->
<script id="descriptionForbooking">"{{ booking.description }}"</script>
<script src="{{ url_for('static', filename='js/services/booking_confirm.js') }}"></script>
<!-- Google recaptcha script-->
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

frontend/templates/services/booking_details.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/booking_details.css') }}">
{% endblock %}

{% block title %}Booking{% endblock %}
{% block header %}{% endblock %}

{% block flashmessage %}
{{ super() }}
{% endblock %}



{% block content %}
<main class="main">
  <form class="col-12" role="submit" method="post" action="/services/booking/recommendation/{{ service_id }}">
    <div class="bar-logo">
      <img src="{{ url_for('static', filename='favicon.ico')}}" alt="">
      <div class="progress" role="progressbar" aria-label="Success example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
      <div class="progress-bar bg-primary" style="width: 0%">0%</div>
      </div>
    </div>

    <h3 class="task-text">{{ service_name }}</h3>

    <div>Tell us about your task, we use this to show you taskers in your area</div>

    <div class="task-location">
      <p class="bold">Task location</p>
      <div class="col-md-4">
        <label for="inputState" class="form-label">State</label>
        <select id="inputState" name="state" class="form-select">
          <option selected>Choose...</option>
          {% if states %}
          {% for state in states %}
          <option value="{{ state }}">{{ state }}</option>
          {% endfor %}
          {% endif %}
        </select>
      </div>
      <div class="col-md-6">
        <label for="inputLGA" class="form-label">LGA</label>
        <select id="inputLGA" name="LGA" class="form-select">
          <option selected>Choose...</option>
          <!-- Dynamically update the la options-->
        </select>
      </div>
      <div class="col-12">
        <label for="inputAddress" class="form-label">Address</label>
        <input type="text" name="address" class="form-control" id="inputAddress" placeholder="1234 Main St">
      </div>
    </div>

    <div class="task-option col-12">
      <p class="bold">Task option</p>
      <p>How big is your task?</p>
      <div class="form-check">
        <input class="form-check-input" type="radio" value="Small - Est. 1hour" name="size" id="small-task">
        <label class="form-check-label" for="small-task">
          Small - Est. 1hour
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" value="Medium - Est. 2-3 hours" type="radio" name="size" id="medium-task" checked>
        <label class="form-check-label" for="medium-task">
          Medium - Est. 2-3 hours
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" value="Large - Est. 4 hours above" type="radio" name="size" id="large-task">
        <label class="form-check-label" for="large-task">
          Large - Est. 4 hours above
        </label>
      </div>
    </div>

    <div class="task-description">
      <p class="bold">Tell us the details of your task</p>
      <p>Start the conversation by telling the tasker what you need to get done
        this helps us show you qualified and available crafter
        Dont worry, you an edit this later
      </p>
      <div class="col-12">
        
        <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3" placeholder="Write what you want the tasker to do for you"></textarea>
      </div>
      <p>If you need two or more crafter, post additional task for each tasker needed</p>
    </div>
    <input type="text" name="serivce_name" value="{{serivce_name}}" hidden>
    <button class="btn btn-outline-primary text-center m-4" id="available-crafter" type="submit">See available crafter</button>
  </form>


</main>

{% endblock %}

{% block footer %}{% endblock %}

{% block scripts %}
{{ super() }}
<script id="LGAData" type="application/json">{{ lga_data | tojson }}</script>
<script src="{{ url_for('static', filename='js/services/booking_details.js') }}"></script>
{% endblock %}

frontend/templates/services/booking_recommendation.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<!-- page css-->
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/booking_recommendation.css') }}">
<!-- Jquery date picker-->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css">
<!-- Jquery time picker-->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
{% endblock %}

{% block title %}Booking{% endblock %}
{% block header %}{% endblock %}

{% block flashmessage %}
{{ super() }}
{% endblock %}



{% block content %}
<main class="main">

  <div class="bar-logo">
    <img src="{{ url_for('static', filename='favicon.ico')}}" alt="">
    <div class="progress" role="progressbar" aria-label="Success example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
    <div class="progress-bar bg-primary" style="width: 50%">50%</div>
    </div>
  </div>
 
  <div id="crafter-boards">
   <!-- Dynamically update crafter boards from jquery-->
  </div>

  

  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog .modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <img src="" alt="" id="arisanImage" class="artisan-image">
          <h1 class="modal-title fs-5 headerTexts" id="staticBackdropLabel headerText">
            <!-- dynamically generate Artisan header text from jquery -->
          </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form id="dateTimeForm" method="post" action="/services/booking/confirm/{{service_id}}">
          <div class="modal-body" id="modalBodyContent" >
            <!-- Form to select date and time -->
            <div class="col-md-6">
              <div id="datePicker"></div>
            </div>
            <div class="col-md-6 mt-3">
              <input type="text" class="timepickera" id="timePicker">
            </div>
            <div>
              <p>Choose your task date and start time. You can chat to adjust task details or change start time after confirming.</p>
            </div>
          </div>
          <!-- Output of date requested for-->
          <div>
             <!-- It is dynamically updated-->
            <p id="date-time-request">You request for: <span class="requestDate"></span> at <span class="requestTime"></span></p>
          </div>
          <div>
            <p>This Tasker requires 2 hour minimum</p>
          </div>
          <div>
            <p>Next, confirm your details to get connected with your Tasker.</p>
          </div>
          <!-- Inpput to be submitted, from jquery dynamic contents-->
          <input type="text" id="date"  name="date" hidden> 
          <input type="text" id="time"  name="time" hidden>
          <input type="text" id="artisanName" name="artisan_name" hidden>
          <input type="text" id="serviceName" name="service_name" hidden>
          <input type="text" id="artisanProfilepicture" name="artisan_profile_picture" hidden>
          <input type="text" id="artisanPrice" name="artisan_price" hidden>
          <input type="text" id="artisanID" name="artisan_id" hidden>
          <!-- Input by user to be submitted from flask--> 
          <input type="text" name="state" value="{{user_task_details.state}}" hidden>
          <input type="text" name="LGA" value="{{user_task_details.LGA}}" hidden>
          <input type="text" name="address" value="{{user_task_details.address}}" hidden>
          <input type="text" name="size" value="{{user_task_details.size}}" hidden>
          <input type="text" name="description" value="{{user_task_details.description}}" hidden>
          <div class="modal-footer">
            <button class="btn btn-secondary text-center" type="submit">
              Select and Continue
            </button>
            <!--<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>-->
          </div>
        </form>
      </div>
    </div>
  </div>
     

  



  <ul id="item-list">
    <!-- Items will be dynamically populated here -->
  </ul>


  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" id="prev" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" id="next" href="#">Next</a></li>
    </ul>
  </nav>


</main>

{% endblock %}

{% block footer %}{% endblock %}



{% block scripts %}
{{ super() }}
<!-- Embedding data in a script tag as JSON -->
<script id="dataForArtisans" type="application/json">{{ artisans | tojson }}</script>
<script id="dataForArtisansUser" type="application/json">{{ artisans_user_data | tojson }}</script>
<script id="serviceType" type="application/json">{{ service_name | tojson }}</script>
<script src="{{ url_for('static', filename='js/services/booking_recommendation.js') }}"></script>
<!-- Jquery date picker-->
<script src="https://code.jquery.com/ui/1.13.3/jquery-ui.js"></script>
<!-- Jquery time picker-->
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
{% endblock %}

frontend/templates/services/booking_schedule.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/booking_schedule.css') }}">
{% endblock %}

{% block title %}Booking{% endblock %}




{% block content %}
<main class="main">
    <section>
        <p>booking_schedule</p>
        <div class="modal-content">
            <span id="closeModalBtn" class="close">&times;</span>
            <h2>Modal Content</h2>
            <!-- Add your modal content here -->
        </div>
        
    </section>

  
 

</main>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/services/booking_schedule.js') }}"></script>
{% endblock %}

frontend/templates/services/booking_success.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/booking_success.css') }}">
{% endblock %}

{% block title %}Booking Confirm{% endblock %}
{% block header %}{% endblock %}

{% block flashmessage %}
{{ super() }}
{% endblock %}



{% block content %}
<main class="main">
  <section>
    <div>
      <p>Successfully booked</p>
      <p>Find below booking details</p>
      <p>Booking ID: {{ response.id}} </p>
      <p>Date: {{response.job_date}}</p>
      <p>Time: {{response.job_time}}</p>
      <p>Address: {{response.job_address}}, {{response.job_LGA}}, {{response.job_state}}.</p>
      <p>Job description: {{ response.job_description }}</p>
      <p>Price: {{response.job_price}}/hr</p>
      <p>Payment Type: {{ response.payment_type }}</p>

      <p>R {{d}}</p>
    </div>
  </section>
    
  



</main>

{% endblock %}

{% block footer %}{% endblock %}

{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename='js/services/booking_success.js') }}"></script>
{% endblock %}

frontend/templates/services/services.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/services/services.css') }}">
{% endblock %}

{% block title %}Services{% endblock %}

{% block headers %} {% endblock %}



{% block content %}
<main>
  <section class="services container">
    <h1>Services offered</h1>
    <div class="card-group" id="service-card">
      <!-- Sample html for the service card
      <div class="card">
        <img src="{{ url_for('static', filename='images/tailor.jpeg') }}" class="card-img-top" alt="...">
        <div class="card-footer">
          <p class="text-body-secondary text-bold">{{ service }}</p>
        </div>
      </div>
      -->
      <!-- Services will be updated dynamically -->
    </div>
    
  </section>
  <!-- Send the services to Jquery for filtering -->
  <script id="services" type="application/json">{{ services | tojson }}</script>
</main>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/services/services.js') }}"></script>
{% endblock %}